---
title: "p8105_hw6_yx2710"
output: html_document
date: "2022-11-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


#Problem2
```{r}
homicide_raw_df = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```


```{r}
homicide_df = 
  homicide_raw_df %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    status = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
      ),
    victim_age = as.numeric(victim_age),
    status_ = as.numeric(status == "solved")
    ) %>% 
    filter(
    city_state != "Dallas,TX" & city_state != "Phoenix,AZ" & city_state != "Kansas City,MO" &
    city_state != "Tulsa,AL" & victim_race %in% c("White","Black"))
    
```

```{r}
bal_df = homicide_df %>% 
  filter(city_state == "Baltimore,MD") 
```

```{r}
bal_fit = 
  glm(status_ ~ victim_age + victim_sex + victim_race, family = binomial(), data = bal_df) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    conf.lower = exp(estimate - 1.96*std.error),
    conf.upper = exp(estimate + 1.96*std.error)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(term,OR, p.value, conf.lower, conf.upper) %>% 
  knitr::kable(digits = 3)
  
bal_fit
```

```{r}
glm_model = function(city_df){
  city_fit = 
    glm(status_ ~ victim_age + victim_sex + victim_race, family = binomial(), data = city_df) %>%
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    conf.lower = exp(estimate - 1.96*std.error),
    conf.upper = exp(estimate + 1.96*std.error)) %>%
  filter(term == "victim_sexMale") %>%
  select(OR, conf.lower, conf.upper)
  
  return(city_fit)
}
```

```{r}
models_df = 
  homicide_df %>% 

  nest(data = -city_state) %>% 
  mutate(
    city_fit = purrr::map(data, glm_model)
  ) %>% 
  select(-data) %>% 
  unnest(city_fit)

models_df %>% 
  knitr::kable(digits = 3)
```

```{r}
models_df %>% 
  mutate(city_state = fct_reorder(city_state,OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.lower, ymax = conf.upper)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  xlab("City, State")+
  ylab("OR for solving homicides comparing male victims to female victims")
```

#Problem 3

```{r}
birth_raw_df = read_csv("birthweight.csv")
```

```{r}
birth_df= 
  birth_raw_df %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace)
  ) %>% 
  drop_na()
```

```{r}
fit_1 = lm(bwt ~ ., data = birth_df)

fit_1 %>% 
  broom::tidy() %>%
   knitr::kable(digit = 3)

backward_model <- step(fit_1, direction="backward")
summary(backward_model)
```
I use the backward stepwise to select the variables in the model and they are babysex, bhead, blength, delwt, gaweeks, mheight, mrace, parity, ppwt and smoken.

```{r}
final_model = lm(bwt ~ babysex + bhead + blength + delwt + gaweeks + mheight + mrace + parity + ppwt + smoken, data = birth_df)
```


```{r}
birth_df %>%
  modelr::add_predictions(final_model) %>%
  modelr::add_residuals(final_model) %>%
  ggplot(aes(y = resid, x = pred)) + 
  geom_point(alpha = 0.3, size = 1) +
  labs(title = "Model residuals against fitted values") +
  xlab("fitted value") + ylab("model residual")
```










